
name: 'ReleaseTag'

on:
  push:
    tags:
      - '*'
permissions:
  contents: read

jobs:
  PR:
    name: 'ReleaseTag'
    runs-on:
      labels: self-hosted
#    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Maven Dependencies
        run: |
          mvn clean package
          mv target/shipping-1.0.jar shipping.jar

      - name: Create Archive
        run: |
          echo $GITHUB_REF_NAME > VERSION
          zip -r catalogue-$GITHUB_REF_NAME.zip shipping.jar VERSION

      - name: Release App
        run: |
          'curl -sSf -u "admin:$Artifactory_PASSWORD" -X PUT -T catalogue-$GITHUB_REF_NAME.zip http://artifactory.devopspv24.online:8081/artifactory/catalogue/catalogue-$GITHUB_REF_NAME.zip'
        env:
          $Artifactory_PASSWORD: ${{  secrets.$Artifactory_PASSWORD }}
